### ISSUE TITLE
in webide not work

### ISSUE THREAD

**Issue by ZubiTechOfficial** [cyan-2048/Discord4KaiOS#1]
i open public folder as packged app install only black screen on my mobile

**Comment by cyan-2048** [comment]
![image](https://user-images.githubusercontent.com/72785466/175254523-a29096e3-c2e5-441d-b07c-fc90bb6cebb8.png)

**Comment by ZubiTechOfficial** [comment]
> Owner
> ### [<img alt="@cyan-2048" width="20" height="20" src="https://avatars.githubusercontent.com/u/72785466?s=60&amp;v=4">](/cyan-2048) ** [cyan-2048](/cyan-2048) ** commented [6 days ago](#issuecomment-1164116164)

i have try but new version not work i have its old version2.0.1 its work but new version not work am used npm run build
